In [8]:
# Imports the Google Cloud client library
from google.cloud import storage

# Instantiates a client
storage_client = storage.Client()
# The ame for the new bucket
bucket_name = 'my-new-bucket'

# Creates the new bucket
bucket = storage_client.create_bucket(bucket_name)

print('Bucket {} created.'.format(bucket.name))

<Bucket: blendo-export-59d68afeb2dc20c025728ed1>
<Bucket: dataflow-staging-us-central1-818651131083>
<Bucket: dw_seeds>
<Bucket: for-test-delete-me>
<Bucket: jaccard>
<Bucket: mktgdw>
<Bucket: ml_data_upload>
<Bucket: mo-dataflow-pipelines>
<Bucket: mo-mercedes>
<Bucket: moda-operandi-dw>
<Bucket: moda-operandi-dw.appspot.com>
<Bucket: staging.moda-operandi-dw.appspot.com>
<Bucket: tims_data>
<Bucket: us.artifacts.moda-operandi-dw.appspot.com>
<Bucket: zaius-event-data>
<Bucket: zaius-parquet-data>

In [9]:
import pandas as pd
import os
from google.cloud import bigquery

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = r"C:\Users\m.young\Documents\BigQueryAPIKey\modata-79d448dbeef0.json"
client = bigquery.Client()

In [10]:
# query
wh_actuals_query = """
SELECT
     *
FROM adhoc_analytics.project_inven_forecast_actuals_EST
  """

# put query results into pandas df
wh_actuals = client.query(wh_actuals_query).to_dataframe()

# replace NaN with 0s
wh_actuals.fillna(0, inplace=True)

In [14]:
wh_actuals.head(50)

# export data to bigquery
wh_actuals.to_gbq('adhoc_analytics.temp_test_py2bq',project_id='moda-operandi-dw',if_exists = 'append')

,date_est,OUT_CUST_UNITS,OUT_TO_UNITS,OUT_VR_UNITS,IN_CUST_UNITS,IN_PO_UNITS,IN_TO_UNITS,TTL_OUT_UNITS,TTL_IN_UNITS,TTL_ALL_UNITS
0,2016-03-17,336,84.0,0.0,150.0,233.0,133.0,420,516,936
1,2016-05-30,251,0.0,0.0,0.0,0.0,0.0,251,0,251
2,2016-06-19,266,0.0,0.0,0.0,0.0,0.0,266,0,266
3,2016-06-27,248,5.0,0.0,126.0,453.0,107.0,253,686,939
4,2016-07-24,155,0.0,0.0,0.0,0.0,0.0,155,0,155
5,2016-11-05,205,0.0,1.0,0.0,0.0,0.0,206,0,206
6,2017-01-03,285,6.0,0.0,127.0,574.0,138.0,291,839,1130
7,2017-01-10,568,22.0,174.0,202.0,1121.0,85.0,764,1408,2172
8,2017-02-28,280,22.0,0.0,159.0,523.0,90.0,302,772,1074
9,2017-03-04,388,1.0,0.0,8.0,678.0,0.0,389,686,1075
10,2017-03-06,533,42.0,0.0,238.0,782.0,38.0,575,1058,1633
11,2017-04-17,447,18.0,0.0,928.0,580.0,51.0,465,1559,2024
12,2017-05-07,567,0.0,0.0,14.0,0.0,0.0,567,14,581
13,2017-09-18,199,85.0,0.0,348.0,633.0,30.0,284,1011,1295
14,2018-01-06,574,0.0,7.0,52.0,0.0,0.0,581,52,633
15,2018-03-13,421,86.0,36.0,625.0,619.0,172.0,543,1416,1959
16,2018-03-16,797,181.0,3.0,338.0,968.0,143.0,981,1449,2430
17,2018-08-20,315,81.0,18.0,276.0,1954.0,10.0,414,2240,2654
18,2018-08-28,330,151.0,51.0,322.0,700.0,92.0,532,1114,1646
19,2018-10-01,347,311.0,0.0,348.0,767.0,254.0,658,1369,2027
20,2018-11-19,1418,297.0,148.0,152.0,942.0,29.0,1863,1123,2986
21,2018-12-21,1120,37.0,207.0,1245.0,1065.0,57.0,1364,2367,3731
22,2019-02-04,1146,104.0,0.0,3.0,1937.0,94.0,1250,2034,3284
23,2019-03-22,602,117.0,10.0,652.0,778.0,12.0,729,1442,2171
24,2019-05-22,2278,153.0,1.0,1568.0,1253.0,69.0,2432,2890,5322
25,2019-07-06,1313,0.0,0.0,877.0,0.0,1.0,1313,878,2191
26,2016-01-27,203,6.0,11.0,129.0,369.0,0.0,220,498,718
27,2016-02-05,182,23.0,83.0,93.0,0.0,0.0,288,93,381
28,2016-03-02,320,69.0,36.0,149.0,219.0,36.0,425,404,829
29,2016-03-05,180,5.0,0.0,106.0,0.0,0.0,185,106,291
30,2016-04-08,700,26.0,0.0,194.0,680.0,16.0,726,890,1616
31,2016-09-02,389,77.0,4.0,276.0,425.0,0.0,470,701,1171
32,2017-01-15,243,0.0,0.0,0.0,0.0,0.0,243,0,243
33,2017-02-16,423,206.0,51.0,340.0,254.0,121.0,680,715,1395
34,2017-04-16,179,77.0,0.0,0.0,0.0,0.0,256,0,256
35,2017-05-28,567,0.0,0.0,360.0,0.0,0.0,567,360,927
36,2017-10-10,440,45.0,0.0,506.0,373.0,53.0,485,932,1417
37,2018-01-25,656,159.0,4.0,346.0,536.0,116.0,819,998,1817
38,2018-02-24,981,4.0,0.0,0.0,597.0,0.0,985,597,1582
39,2018-04-08,528,0.0,0.0,0.0,0.0,0.0,528,0,528
40,2018-07-10,377,103.0,5.0,381.0,212.0,308.0,485,901,1386
41,2018-08-11,576,0.0,0.0,0.0,0.0,0.0,576,0,576
42,2018-09-01,359,22.0,0.0,10.0,521.0,97.0,381,628,1009
43,2018-11-06,464,192.0,9.0,271.0,830.0,147.0,665,1248,1913
44,2018-12-18,800,158.0,62.0,1104.0,891.0,108.0,1020,2103,3123
45,2019-02-27,454,241.0,26.0,307.0,735.0,2.0,721,1044,1765
46,2019-03-05,519,72.0,2.0,57.0,1422.0,147.0,593,1626,2219
47,2019-05-18,3057,29.0,43.0,388.0,0.0,0.0,3129,388,3517
48,2019-06-29,1268,16.0,51.0,65.0,0.0,0.0,1335,65,1400
49,2016-02-07,89,0.0,0.0,0.0,0.0,0.0,89,0,89

In [ ]:
# self.result.columns = [i.lower().replace(' ','_').replace('%','pct') for i in list(self.result.columns.values)]
# self.result = self.result.sort_values(by="ds")
# self.result.loc[:,["ds","yhat","yhat_lower","yhat_upper","forecast_type","forecast_timestamp"]].\
# to_gbq('adhoc_analytics.ds_forecast__warehouse_traffic',project_id='moda-operandi-dw',if_exists = 'append')

1it [00:05,  5.20s/it]